# æ–‡ç« 
nav:
  - JIAO:
    - About:            index.md
    - æˆ‘è¿™ä¸€ç”Ÿå¦‚å±¥è–„å†°:    src/about/honor.md
  - ğŸª‚ Algorithm:
    - Pre:              src/algorithm/pre.md
    - CSP:              src/algorithm/really/csp.md
    - GESP:             src/algorithm/really/gesp.md
    - CIE:              src/algorithm/really/cie.md
    - åŸºç¡€:
      - äºŒåˆ†:           src/algorithm/åŸºç¡€/äºŒåˆ†.md
    - æœç´¢:
      - DFS:            src/algorithm/æœç´¢/DFS.md
    - å›¾è®º:
      - äºŒå‰æ ‘:         src/algorithm/å›¾è®º/äºŒå‰æ ‘.md
    #- åŠ¨è§„:
    #- æ•°å­¦:
    #- æ•°è®º:
    - æ•°æ®ç»“æ„:
      - é“¾è¡¨:           src/algorithm/æ•°æ®ç»“æ„/é“¾è¡¨.md
      - çº¿æ®µæ ‘:         src/algorithm/æ•°æ®ç»“æ„/çº¿æ®µæ ‘.md
    #- å­—ç¬¦ä¸²:
    #- è®¡ç®—å‡ ä½•:
  - ğŸš€ C/C++:
    - CPP:              src/cpp/cpp.md
    - STL:              src/cpp/stl.md
    - Thread:           src/cpp/thread.md
    - Network:          src/cpp/network.md
    - GUI:              src/cpp/gui.md
    - AV:               src/cpp/av.md
    - ROS:              src/cpp/ros.md
  - ğŸŒ¥ï¸ DevOps:  
    - ğŸ«¥ Cloud:         src/dev/cloud.md
    - ğŸ«¥ MkDocs:        src/dev/mkdocs.md
    - ğŸ˜³ GCC:           src/dev/gcc.md
    - ğŸ˜³ GDB:           src/dev/gdb.md
    - ğŸ˜³ Make:          src/dev/make.md
    - ğŸ˜³ CMake:         src/dev/cmake.md
    - ğŸ˜³ Perf:          src/dev/perf.md
    - ğŸ˜³ Boost:         src/dev/boost.md
    - ğŸ˜³ OpenSSL:       src/dev/openssl.md
    - ğŸ˜³ FFmpeg:        src/dev/ffmpeg.md
    - ğŸ˜³ Qt:            src/dev/qt.md
    - ğŸ’ªğŸ» OpenSSH:       src/dev/openssh.md
    - ğŸ’ªğŸ» Git:           src/dev/git.md
    - ğŸ’ªğŸ» Docker:        src/dev/docker.md
    - ğŸ’ªğŸ» Kubernetes:    src/dev/kubernetes.md
    - ğŸ’ªğŸ» Nginx:         src/dev/nginx.md
    - ğŸª– Coturn:        src/dev/coturn.md
    - ğŸª– FRP:           src/dev/frp.md
    - ğŸª– DDNS:          src/dev/ddns.md
    - ğŸ“’ MySQL:         src/dev/mysql.md
    - ğŸ“’ Redis:         src/dev/redis.md
  - ğŸŒ¿ Language:
    - Python:
      - env:            src/language/py/env.md
      - pandas:         src/language/py/pandas.md
      - openpyxl:       src/language/py/openpyxl.md
      - tornado:        src/language/py/tornado.md
    - Golang:
      - go:             src/language/go/go.md
      - gin:            src/language/go/gin.md
      - websocket:      src/language/go/websocket.md
    - JS:
      - websocket:      src/language/js/websocket.md
      - webrtc:         src/language/js/webrtc.md
    - Java:
      - main/java:      src/language/java/main_java.md
      - main/resources: src/language/java/main_resources.md
      - test/java:      src/language/java/test_java.md
    - HTML:
      - HTML:           src/language/html/html.md
      - CSS:            src/language/html/css.md
  - ğŸ“– CS:
    - æ“ä½œç³»ç»Ÿ:
      - linuxé€ŸæŸ¥:      src/cs/os/quick_linux.md
      - æ“ä½œç³»ç»Ÿç»“æ„:    src/cs/os/æ“ä½œç³»ç»Ÿç»“æ„.md
    - ç½‘ç»œ:
      - å†²æµª:           src/cs/net/å†²æµª.md
      - Application:
        - HTTP:         src/cs/net/http.md
      - Transport:
        - TCP:          src/cs/net/tcp.md
        - UDP:          src/cs/net/udp.md
      - Network:
        - IPv4:         src/cs/net/ipv4.md
      - DataLink:
        - Ethernet:     src/cs/net/ethernet.md
        - PPPoE:        src/cs/net/pppoe.md
        - MTU:          src/cs/net/mtu.md
    - æ•°æ®ç»“æ„:
      - çº¿æ€§è¡¨:         src/cs/dataStruct/list.md
    - æ•°æ®åº“: 
      - mysqlé€ŸæŸ¥:      src/cs/dataBase/quick_mysql.md
    - è®¾è®¡æ¨¡å¼:         src/cs/designPattern/designPattern.md
    - ç³»ç»Ÿæ¶æ„:         src/cs/systemArchitecture/systemArchitecture.md
    - å·¥ç¨‹å¸ˆ:           src/cs/engineer/engineer.md
  - ğŸ”¢ Math:
    - å¾®ç§¯åˆ†:           src/math/å¾®ç§¯åˆ†.md
    - æ¦‚ç‡è®º:           src/math/æ¦‚ç‡è®º.md
  - ğŸ‘· Î¦Î¹Î»Î¿ÏƒÎ¿Ï†Î¯Î±:
    - é©¬å…‹æ€ä¸»ä¹‰:       src/philosophy/marx.md
    - ä¸­å›½è¿‘ä»£å²:       src/philosophy/historyOfChina.md
  - ğŸ•¶ï¸ More:
    - GenRNA3D:         src/more/xd.md






site_name: æˆ´å…´é¾™
copyright: ç‰ˆæƒæ‰€æœ‰ Â© 2020 - 2024 å…¨ä¸–ç•Œæ— äº§é˜¶çº§æˆ˜å£«
repo_name: daixll/daixll.github.io
repo_url: https://github.com/daixll/daixll.github.io

theme:
  logo: assets/head.png     # ä¸»å›¾æ ‡
  favicon: assets/head.png  # æ ‡ç­¾æ å›¾æ ‡
  name: material            # ä¸»é¢˜
  language: 'zh'            # ä¸­æ–‡ç½‘ç«™
  palette:                  # æ˜/æš—æ¨¡å¼
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:                 # åŠŸèƒ½
    - navigation.top        # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.tabs       # é¡¶éƒ¨å¯¼èˆª
    - content.code.copy     # ä»£ç å¤åˆ¶
  font:
    text: 'Noto Serif SC'   # å­—ä½“
    code: 'Fira Mono'       # ä»£ç å­—ä½“

extra:
  generator: false          # æ˜¯å¦æ˜¾ç¤º Made with Material for MkDocs
  social:                   # å³ä¸‹è§’å°æ ‡
    - icon: fontawesome/solid/paper-plane
      link: mailto:<dxlcq@outlook.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.details        # è¯¦æƒ…æŠ˜å æ‰©å±•
  # ä»£ç å—
  - pymdownx.superfences    # ä»£ç å—å¤„ç†
  - pymdownx.highlight:     # ä»£ç å—é«˜äº®
      linenums: true        # æ˜¾ç¤ºè¡Œå·
      auto_title: true      # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  # latex
  - pymdownx.arithmatex:
      generic: true         # å¯ç”¨é€šç”¨çš„æ•°å­¦å…¬å¼æ”¯æŒ è²Œä¼¼æ˜¯ $$ çš„æ”¯æŒ

