site_name: æˆ´å…´é¾™
copyright: Copyright Â© 2020 - 2024 Xinglong Dai
repo_name: daixll/daixll.github.io
repo_url: https://github.com/daixll/daixll.github.io



theme:
  logo: assets/head.png     # ä¸»å›¾æ ‡
  favicon: assets/head.png  # æ ‡ç­¾æ å›¾æ ‡
  name: material            # ä¸»é¢˜
  language: 'zh'            # ä¸­æ–‡ç½‘ç«™
  palette:                  # æ˜/æš—æ¨¡å¼
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:                 # åŠŸèƒ½
    - navigation.top    # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.tabs   # é¡¶éƒ¨å¯¼èˆª
    - content.code.copy # ä»£ç å¤åˆ¶
  font:
    text: 'Noto Serif SC' # å­—ä½“
    code: 'Fira Mono'     # ä»£ç å­—ä½“

# æ’ä»¶
plugins:
  - search

markdown_extensions:
  - toc:                    # ä¾§è¾¹ç›®å½•
      permalink: true                                 # å¯ç”¨ç›®å½•é¡¹çš„æ°¸ä¹…é“¾æ¥åŠŸèƒ½
      slugify: !!python/name:pymdownx.slugs.uslugify  # æ ‡é¢˜ç”Ÿæˆæ°¸ä¹…é“¾æ¥çš„æ–¹å¼
  - pymdownx.superfences:   # ?
      custom_fences:                                  # è‡ªå®šä¹‰ä»£ç å—
        - name: mermaid                                                 # è‡ªå®šä¹‰ä»£ç å—çš„åç§°
          format: !!python/name:pymdownx.superfences.fence_code_format  # å¦‚ä½•æ ¼å¼åŒ– mermaid ä»£ç å—
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra:
  generator: false    # åˆ é™¤ Made with Material for MkDocs

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# æ–‡ç« 
nav:
  - JIAO:
    - About: index.md
    - Project: src/about/project.md
    - Work: src/about/work.md
    - Education: src/about/education.md
    - Honor: src/about/Honor.md
  - ğŸª‚ Algorithm:
    - å…¥é—¨: a.md
    - åŸºç¡€: a.md
  - ğŸš€ C/C++:
    - moderncpp:
      - Item 2: cpp/moderncpp.md
      - Item 3: d.md
  - ğŸŒ¥ï¸ DevOps:
    - å¼€å‘ç¯å¢ƒ: a.md
    - å¸¸ç”¨è½¯ä»¶: a.md
  - ğŸŒ¿ Language:
    - Python:
      - xxi: 123.md
      - xxx: sas.md
    - Golang:
      - xixi: aaa.md
      - jiji: kkk.md
  - ğŸ“– CS:
    - æ•°æ®ç»“æ„: a.md
    - æ“ä½œç³»ç»Ÿ: a.md
  - ğŸ”¢ Math:
    - å¾®ç§¯åˆ†:
    - æ¦‚ç‡è®º:
  - ğŸ‘· Î¦Î¹Î»Î¿ÏƒÎ¿Ï†Î¯Î±:
    - é©¬å…‹æ€ä¸»ä¹‰: a.md
