# æ–‡ç« 
nav:
  - JIAO:
    - About:            index.md
    - Work:             src/about/work.md
    - Project:          src/about/project.md
    - Education:        src/about/education.md
    - Honor:            src/about/honor.md
  - ğŸª‚ Algorithm:
    - å…¥é—¨:             src/algorithm/start/å…¥é—¨.md
    - åŸºç¡€:
      - äºŒåˆ†:           src/algorithm/base/äºŒåˆ†.md
    - æœç´¢:             src/algorithm/base/äºŒåˆ†.md
    - å›¾è®º:             src/algorithm/base/äºŒåˆ†.md
    - åŠ¨è§„:             src/algorithm/base/äºŒåˆ†.md
    - æ•°å­¦:             src/algorithm/base/äºŒåˆ†.md
    - æ•°è®º:             src/algorithm/base/äºŒåˆ†.md
    - æ•°æ®ç»“æ„:         src/algorithm/base/äºŒåˆ†.md
    - å­—ç¬¦ä¸²:           src/algorithm/base/äºŒåˆ†.md
    - è®¡ç®—å‡ ä½•:         src/algorithm/base/äºŒåˆ†.md
  - ğŸš€ C/C++:
    - C:                src/cpp/c.md
    - CPP:              src/cpp/cpp.md
    - STL:              src/cpp/stl.md
    - Thread:           src/cpp/thread.md
    - Network:          src/cpp/network.md
    - GUI:              src/cpp/gui.md
    - AV:               src/cpp/av.md
  - ğŸŒ¥ï¸ DevOps:  
    - BASE:             src/dev/dev.md
    - GCC:              src/dev/gcc.md
    - GDB:              src/dev/gdb.md
    - Make:             src/dev/make.md
    - CMake:            src/dev/cmake.md
    - Boost:            src/dev/boost.md
    - OpenSSL:          src/dev/openssl.md
    - FFmpeg:           src/dev/ffmpeg.md
    - Qt:               src/dev/qt.md
    - OpenSSH:          src/dev/openssh.md
    - Git:              src/dev/git.md
    - Docker:           src/dev/docker.md
    - Kubernetes:       src/dev/kubernetes.md
    - Nginx:            src/dev/nginx.md
    - Perf:             src/dev/perf.md
    - nc:               src/dev/nc.md
    - nmap:             src/dev/nmap.md
    - MySQL:            src/dev/mysql.md
    - Redis:            src/dev/redis.md
  - ğŸŒ¿ Language:
    - Python:
      - env:            src/language/py/env.md
      - pandas:         src/language/py/pandas.md
      - openpyxl:       src/language/py/openpyxl.md
      - tornado:        src/language/py/tornado.md
    - Golang:
      - go:             src/language/go/go.md
      - gin:            src/language/go/gin.md
    - Java:
      - main/java:      src/language/java/main_java.md
      - main/resources: src/language/java/main_resources.md
      - test/java:      src/language/java/test_java.md
    - HTML:
      - HTML:           src/language/html/html.md
      - CSS:            src/language/html/css.md
      - JS:             src/language/html/js.md
  - ğŸ“– CS:
    - æ“ä½œç³»ç»Ÿ:
      - linuxé€ŸæŸ¥:      src/cs/os/quick_linux.md
      - æ“ä½œç³»ç»Ÿç»“æ„:    src/cs/os/æ“ä½œç³»ç»Ÿç»“æ„.md
    - æ•°æ®ç»“æ„:
      - çº¿æ€§è¡¨:         src/cs/dataStruct/list.md
    - æ•°æ®åº“: 
      - mysqlé€ŸæŸ¥:      src/cs/dataBase/quick_mysql.md
    - è®¾è®¡æ¨¡å¼:         src/cs/designPattern.md
    - ç³»ç»Ÿæ¶æ„:         src/cs/systemArchitecture/systemArchitecture.md
    - å·¥ç¨‹å¸ˆ:           src/cs/engineer.md
  - ğŸ”¢ Math:
    - å¾®ç§¯åˆ†:           src/math/å¾®ç§¯åˆ†.md
    - æ¦‚ç‡è®º:           src/math/æ¦‚ç‡è®º.md
  - ğŸ‘· Î¦Î¹Î»Î¿ÏƒÎ¿Ï†Î¯Î±:
    - é©¬å…‹æ€ä¸»ä¹‰:       src/philosophy/marx.md
    - ä¸­å›½è¿‘ä»£å²:       src/philosophy/historyOfChina.md
  - ğŸ•¶ï¸ More:
    - GenRNA3D:         src/more/xd.md






site_name: æˆ´å…´é¾™
copyright: Copyright Â© 2020 - 2024 Xinglong Dai
repo_name: daixll/daixll.github.io
repo_url: https://github.com/daixll/daixll.github.io

theme:
  logo: assets/head.png     # ä¸»å›¾æ ‡
  favicon: assets/head.png  # æ ‡ç­¾æ å›¾æ ‡
  name: material            # ä¸»é¢˜
  language: 'zh'            # ä¸­æ–‡ç½‘ç«™
  palette:                  # æ˜/æš—æ¨¡å¼
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:                 # åŠŸèƒ½
    - navigation.top        # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.tabs       # é¡¶éƒ¨å¯¼èˆª
    - content.code.copy     # ä»£ç å¤åˆ¶
  font:
    text: 'Noto Serif SC'   # å­—ä½“
    code: 'Fira Mono'       # ä»£ç å­—ä½“

extra:
  generator: false          # æ˜¯å¦æ˜¾ç¤º Made with Material for MkDocs
  social:                   # å³ä¸‹è§’å°æ ‡
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/dxlcqy
    - icon: fontawesome/brands/github
      link: https://github.com/daixll
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/35306765
    - icon: fontawesome/solid/paper-plane
      link: mailto:<dxlcq@outlook.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.details        # è¯¦æƒ…æŠ˜å æ‰©å±•
  # ä»£ç å—
  - pymdownx.superfences    # ä»£ç å—å¤„ç†
  - pymdownx.highlight:     # ä»£ç å—é«˜äº®
      linenums: true        # æ˜¾ç¤ºè¡Œå·
      auto_title: true      # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  # latex
  - pymdownx.arithmatex:
      generic: true         # å¯ç”¨é€šç”¨çš„æ•°å­¦å…¬å¼æ”¯æŒ è²Œä¼¼æ˜¯ $$ çš„æ”¯æŒ

