# æ–‡ç« 
nav:
  - éª„:               index.md
  - ğŸª‚ Algorithm:
    - Pre:              src/algorithm/pre.md
    - CSP:              src/algorithm/really/csp.md
    - GESP:             src/algorithm/really/gesp.md
    - CIE:              src/algorithm/really/cie.md
    - åŸºç¡€:
      - äºŒåˆ†:           src/algorithm/base/binary-answer.md
    - æœç´¢:
      - æ·±æœ:            src/algorithm/search/DFS.md
    - å›¾è®º:
      - äºŒå‰æ ‘:         src/algorithm/graph/binary-tree.md
    - åŠ¨è§„:
      - æ•°å­—ä¸‰è§’å½¢:     src/algorithm/dp/number-triangles.md
      #- å­åºåˆ—æ¨¡å‹:     src/algorithm/dp/subsequence.md
      #- èƒŒåŒ…é—®é¢˜:       src/algorithm/dp/knapsack.md
      #- çŠ¶æ€æœº:         src/algorithm/dp/state-machine.md
      #- çº¿æ€§DP:         src/algorithm/dp/linear-dp.md
      #- çŠ¶å‹DP:         src/algorithm/dp/state-compression.md
    #- æ•°å­¦:
    #- æ•°è®º:
    - æ•°æ®ç»“æ„:
      - é“¾è¡¨:           src/algorithm/data-struct/linked-list.md
      - çº¿æ®µæ ‘:         src/algorithm/data-struct/segment-tree.md
    #- å­—ç¬¦ä¸²:
    #- è®¡ç®—å‡ ä½•:
  - ğŸš€ C/C++:
    - CPP:              src/cpp/cpp.md
    - STL:              src/cpp/stl.md
    - Thread:           src/cpp/thread.md
    - Network:          src/cpp/network.md
    - GUI:              src/cpp/gui.md
    - AV:               src/cpp/av.md
    - ROS:              src/cpp/ros.md
    - ğŸ”© GCC:           src/cpp/gcc.md
    - ğŸ”© GDB:           src/cpp/gdb.md
    - ğŸ”© Make:          src/cpp/make.md
    - ğŸ”© CMake:         src/cpp/cmake.md
    - ğŸ”© GTest:         src/cpp/gtest.md
    - ğŸ”© Perf:          src/cpp/perf.md
    - ğŸ”© Boost:         src/cpp/boost.md
    - ğŸ”© OpenSSL:       src/cpp/openssl.md
    - ğŸ”© FFmpeg:        src/cpp/ffmpeg.md
    - ğŸ”© Qt:            src/cpp/qt.md
  - ğŸŒ¥ï¸ DevOps:
    - Cloud:            src/dev/cloud.md
    - ğŸ§ Linux:         src/dev/linux.md
    - ğŸ§‘â€ğŸ’» MacOS:         src/dev/macos.md

    # ğŸ“‹ plan
    # ğŸ’» code
    # ğŸ”¨ build
    # ğŸ§ª test
    # ğŸ“¦ release
    # ğŸš€ deploy
    # ğŸ”§ operation:
    # ğŸ“Š monitor:

    - ğŸ’» Git:           src/dev/git.md
    #- ğŸ’»GitLab:        src/dev/gitlab.md
    - ğŸ”¨ Docker:        src/dev/docker.md
    - ğŸ”¨ Containerd:    src/dev/containerd.md
    - ğŸš€ Kubernetes:    src/dev/kubernetes.md
    - ğŸš€ Nginx:         src/dev/nginx.md

    - ğŸ’ªğŸ» OpenSSH:       src/dev/openssh.md
    - ğŸ’ªğŸ» Coturn:        src/dev/coturn.md
    - ğŸ’ªğŸ» FRP:           src/dev/frp.md
    - ğŸ’ªğŸ» DDNS:          src/dev/ddns.md
    - ğŸ’ªğŸ» MySQL:         src/dev/mysql.md
  - ğŸŒ¿ Language:
    - Python:
      - env:            src/language/py/env.md
      - pandas:         src/language/py/pandas.md
      - openpyxl:       src/language/py/openpyxl.md
      - tornado:        src/language/py/tornado.md
      - deeplearning:   src/language/py/deeplearning.md
    - Golang:
      - go:             src/language/go/go.md
      - gin:            src/language/go/gin.md
      - websocket:      src/language/go/websocket.md
    - JS:
      - websocket:      src/language/js/websocket.md
      - webrtc:         src/language/js/webrtc.md
    - Java:
      - main/java:      src/language/java/main_java.md
      - main/resources: src/language/java/main_resources.md
      - test/java:      src/language/java/test_java.md
    - HTML:
      - HTML:           src/language/html/html.md
      - CSS:            src/language/html/css.md
  - ğŸ“– CS:
    - æ“ä½œç³»ç»Ÿ:
      - æ“ä½œç³»ç»Ÿç»“æ„:    src/cs/os/æ“ä½œç³»ç»Ÿç»“æ„.md
    - ç½‘ç»œ:
      - å†²æµª:           src/cs/net/å†²æµª.md
      - Application:
        - HTTP:         src/cs/net/http.md
      - Transport:
        - TCP:          src/cs/net/tcp.md
        - UDP:          src/cs/net/udp.md
      - Network:
        - IPv4:         src/cs/net/ipv4.md
      - DataLink:
        - Ethernet:     src/cs/net/ethernet.md
        - PPPoE:        src/cs/net/pppoe.md
        - MTU:          src/cs/net/mtu.md
    - æ•°æ®ç»“æ„:
      - çº¿æ€§è¡¨:         src/cs/dataStruct/list.md
    - æ•°æ®åº“: 
      - ç¬¬ä¸€ç« :         src/cs/dataBase/t.md
    - è®¾è®¡æ¨¡å¼:         src/cs/designPattern/designPattern.md
    - ç³»ç»Ÿæ¶æ„:         src/cs/systemArchitecture/systemArchitecture.md
    - å·¥ç¨‹å¸ˆ:           src/cs/engineer/engineer.md
  - ğŸ‘· Î¦Î¹Î»Î¿ÏƒÎ¿Ï†Î¯Î±:
    - é©¬å…‹æ€ä¸»ä¹‰:       src/philosophy/marx.md
    - ä¸­å›½è¿‘ä»£å²:       src/philosophy/historyOfChina.md
  - ğŸ•¶ï¸ More:
    - GenRNA3D:        src/more/xd.md
    - å¾®ç§¯åˆ†:           src/more/å¾®ç§¯åˆ†.md
    - æ¦‚ç‡è®º:           src/more/æ¦‚ç‡è®º.md






site_name: æˆ´å…´é¾™
copyright: ç‰ˆæƒæ‰€æœ‰ Â© 2020 - 2024 å…¨ä¸–ç•Œæ— äº§é˜¶çº§æˆ˜å£«
repo_name: daixll/daixll.github.io
repo_url: https://github.com/daixll/daixll.github.io

theme:
  logo: assets/head.png     # ä¸»å›¾æ ‡
  favicon: assets/head.png  # æ ‡ç­¾æ å›¾æ ‡
  name: material            # ä¸»é¢˜
  language: 'zh'            # ä¸­æ–‡ç½‘ç«™
  palette:                  # æ˜/æš—æ¨¡å¼
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:                 # åŠŸèƒ½
    - navigation.top        # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.tabs       # é¡¶éƒ¨å¯¼èˆª
    - content.code.copy     # ä»£ç å¤åˆ¶
  font:
    text: 'Noto Serif SC'   # å­—ä½“
    code: 'Fira Mono'       # ä»£ç å­—ä½“

extra:
  generator: false          # æ˜¯å¦æ˜¾ç¤º Made with Material for MkDocs
  #social:                   # å³ä¸‹è§’å°æ ‡
  #  - icon: fontawesome/solid/paper-plane
  #    link: mailto:<dxlcq@outlook.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.details        # è¯¦æƒ…æŠ˜å æ‰©å±•
  # ä»£ç å—
  - pymdownx.superfences    # ä»£ç å—å¤„ç†
  - pymdownx.highlight:     # ä»£ç å—é«˜äº®
      linenums: true        # æ˜¾ç¤ºè¡Œå·
      auto_title: true      # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  # latex
  - pymdownx.arithmatex:
      generic: true         # å¯ç”¨é€šç”¨çš„æ•°å­¦å…¬å¼æ”¯æŒ è²Œä¼¼æ˜¯ $$ çš„æ”¯æŒ

