# æ–‡ç« 
nav:
  - JIAO:
    - About:            index.md
    - Project:          src/about/project.md
    - Work:             src/about/work.md
    - Education:        src/about/education.md
    - Honor:            src/about/Honor.md
  - ğŸª‚ Algorithm:
    - å…¥é—¨: _index.md
    - åŸºç¡€: _index.md
  - ğŸš€ C/C++:
    - c:
      - base:           src/cpp/c.md
    - moderncpp:
      - CPP:            _index.md
  - ğŸŒ¥ï¸ DevOps:
    - ğŸ’»:               src/dev/dev.md
    - GCC:              src/dev/gcc.md
    - OpenSSL:          src/dev/openssl.md
    - MySQL:            src/dev/mysql.md
  - ğŸŒ¿ Language:
    - Python: _index.md
    - Golang: _index.md
    - Java:
      - main/java:      src/language/java/main_java.md
      - main/resources: src/language/java/main_resources.md
      - test/java:      src/language/java/test_java.md
  - ğŸ“– CS:
    - æ•°æ®åº“: 
      - mysqlé€ŸæŸ¥:      src/cs/database/quick_mysql.md
    - æ•°æ®ç»“æ„: _index.md
    - æ“ä½œç³»ç»Ÿ: _index.md
  - ğŸ”¢ Math:
    - å¾®ç§¯åˆ†: _index.md
    - æ¦‚ç‡è®º: _index.md
  - ğŸ‘· Î¦Î¹Î»Î¿ÏƒÎ¿Ï†Î¯Î±:
    - é©¬å…‹æ€ä¸»ä¹‰:       src/philosophy/marx.md






site_name: æˆ´å…´é¾™
copyright: Copyright Â© 2020 - 2024 Xinglong Dai
repo_name: daixll/daixll.github.io
repo_url: https://github.com/daixll/daixll.github.io

theme:
  logo: assets/head.png     # ä¸»å›¾æ ‡
  favicon: assets/head.png  # æ ‡ç­¾æ å›¾æ ‡
  name: material            # ä¸»é¢˜
  language: 'zh'            # ä¸­æ–‡ç½‘ç«™
  palette:                  # æ˜/æš—æ¨¡å¼
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:                 # åŠŸèƒ½
    - navigation.top        # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.tabs       # é¡¶éƒ¨å¯¼èˆª
    - content.code.copy     # ä»£ç å¤åˆ¶
  font:
    text: 'Noto Serif SC'   # å­—ä½“
    code: 'Fira Mono'       # ä»£ç å­—ä½“

extra:
  generator: false          # æ˜¯å¦æ˜¾ç¤º Made with Material for MkDocs
  social:                   # å³ä¸‹è§’å°æ ‡
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/dxlcqy
    - icon: fontawesome/brands/github
      link: https://github.com/daixll
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/35306765
    - icon: fontawesome/solid/paper-plane
      link: mailto:<dxlcq@outlook.com>

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.details        # è¯¦æƒ…æŠ˜å æ‰©å±•
  # ä»£ç å—
  - pymdownx.superfences    # ä»£ç å—å¤„ç†
  - pymdownx.highlight:     # ä»£ç å—é«˜äº®
      linenums: true        # æ˜¾ç¤ºè¡Œå·
      auto_title: true      # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  # latex
  - pymdownx.arithmatex:
      generic: true         # å¯ç”¨é€šç”¨çš„æ•°å­¦å…¬å¼æ”¯æŒ è²Œä¼¼æ˜¯ $$ çš„æ”¯æŒ

